//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.micen.buyers.view.home;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import android.widget.ViewFlipper;
import com.focustech.common.widget.HorizontalListView;
import com.micen.buyers.activity.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class EasySourcingFragment_
    extends EasySourcingFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.easy_sourcing_fragment_layout, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static EasySourcingFragment_.FragmentBuilder_ builder() {
        return new EasySourcingFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        btnGallery = ((Button) hasViews.findViewById(com.micen.buyers.activity.R.id.btn_easy_gallery));
        btnPostSourcing = ((Button) hasViews.findViewById(com.micen.buyers.activity.R.id.btn_postsourcing_now));
        horizontalListView = ((HorizontalListView) hasViews.findViewById(com.micen.buyers.activity.R.id.home_recommend_list));
        tv_todayrequests = ((TextView) hasViews.findViewById(com.micen.buyers.activity.R.id.tv_todayrequests));
        btnCamera = ((Button) hasViews.findViewById(com.micen.buyers.activity.R.id.btn_easy_camera));
        titleText = ((TextView) hasViews.findViewById(com.micen.buyers.activity.R.id.common_title_name));
        flipper = ((ViewFlipper) hasViews.findViewById(com.micen.buyers.activity.R.id.view_flipper));
        btnDescribe = ((Button) hasViews.findViewById(com.micen.buyers.activity.R.id.btn_easy_describe));
        initView();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public EasySourcingFragment build() {
            EasySourcingFragment_ fragment_ = new EasySourcingFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
