//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.micen.buyers.view.home;

import android.os.Bundle;
import android.support.v4.widget.SwipeRefreshLayout;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.micen.buyers.activity.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MyAccountFragment_
    extends MyAccountFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.my_account_fragment_layout, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MyAccountFragment_.FragmentBuilder_ builder() {
        return new MyAccountFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        favCompNum = ((TextView) hasViews.findViewById(com.micen.buyers.activity.R.id.tv_vo_supplier_num));
        btnMessage = ((LinearLayout) hasViews.findViewById(com.micen.buyers.activity.R.id.ll_vo_messages));
        messageNum = ((TextView) hasViews.findViewById(com.micen.buyers.activity.R.id.tv_vo_message_num));
        title = ((TextView) hasViews.findViewById(com.micen.buyers.activity.R.id.tv_vo_title));
        favCateNum = ((TextView) hasViews.findViewById(com.micen.buyers.activity.R.id.tv_vo_category_num));
        refreshLayout = ((SwipeRefreshLayout) hasViews.findViewById(com.micen.buyers.activity.R.id.my_account_pull_refresh_scrollview));
        btnSourcing = ((TextView) hasViews.findViewById(com.micen.buyers.activity.R.id.tv_vo_sourcing));
        bgTitle = ((ImageView) hasViews.findViewById(com.micen.buyers.activity.R.id.bg_vo_title));
        btnMember = ((TextView) hasViews.findViewById(com.micen.buyers.activity.R.id.tv_vo_member));
        btnSuppliers = ((RelativeLayout) hasViews.findViewById(com.micen.buyers.activity.R.id.rl_vo_supplier));
        btnLogin = ((TextView) hasViews.findViewById(com.micen.buyers.activity.R.id.tv_vo_unlogin));
        quotationNum = ((TextView) hasViews.findViewById(com.micen.buyers.activity.R.id.tv_vo_quotation_num));
        btnProducts = ((RelativeLayout) hasViews.findViewById(com.micen.buyers.activity.R.id.rl_vo_product));
        btnQuotation = ((LinearLayout) hasViews.findViewById(com.micen.buyers.activity.R.id.ll_vo_quotations));
        btnCategories = ((RelativeLayout) hasViews.findViewById(com.micen.buyers.activity.R.id.rl_vo_category));
        accountName = ((TextView) hasViews.findViewById(com.micen.buyers.activity.R.id.tv_vo_login));
        favProdNum = ((TextView) hasViews.findViewById(com.micen.buyers.activity.R.id.tv_vo_product_num));
        btnSetting = ((ImageView) hasViews.findViewById(com.micen.buyers.activity.R.id.btn_vo_setting));
        initView();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public MyAccountFragment build() {
            MyAccountFragment_ fragment_ = new MyAccountFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
