//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.micen.buyers.view.home;

import android.content.res.Resources;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import com.micen.buyers.activity.R.array;
import com.micen.buyers.activity.R.layout;
import com.micen.buyers.widget.flowlayout.FlowLayout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class SearchFragment_
    extends SearchFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.search_fragment_layout, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        Resources resources_ = getActivity().getResources();
        searchTypes = resources_.getStringArray(array.search_type);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static SearchFragment_.FragmentBuilder_ builder() {
        return new SearchFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        searchEditText = ((EditText) hasViews.findViewById(com.micen.buyers.activity.R.id.keyword_edit_text));
        recentSearchList = ((ListView) hasViews.findViewById(com.micen.buyers.activity.R.id.search_recent_list));
        searchTypeTx = ((TextView) hasViews.findViewById(com.micen.buyers.activity.R.id.search_type));
        searchButton = ((TextView) hasViews.findViewById(com.micen.buyers.activity.R.id.search_btn));
        editTitleLayout = ((RelativeLayout) hasViews.findViewById(com.micen.buyers.activity.R.id.edit_title));
        allCategoryListView = ((ListView) hasViews.findViewById(com.micen.buyers.activity.R.id.category_list_view));
        suggestLayout = ((LinearLayout) hasViews.findViewById(com.micen.buyers.activity.R.id.search_suggest_layout));
        clearImage = ((ImageView) hasViews.findViewById(com.micen.buyers.activity.R.id.clear_keyword));
        suggestList = ((ListView) hasViews.findViewById(com.micen.buyers.activity.R.id.search_suggest_list));
        recentCategoryLayout = ((LinearLayout) hasViews.findViewById(com.micen.buyers.activity.R.id.recent_layout));
        searchLayout = ((RelativeLayout) hasViews.findViewById(com.micen.buyers.activity.R.id.search_title_layout));
        deleteRecentCat = ((ImageView) hasViews.findViewById(com.micen.buyers.activity.R.id.delete_category_btn));
        recentLayout = ((LinearLayout) hasViews.findViewById(com.micen.buyers.activity.R.id.search_recent_layout));
        categoryLayout = ((ScrollView) hasViews.findViewById(com.micen.buyers.activity.R.id.category_layout));
        flowLayout = ((FlowLayout) hasViews.findViewById(com.micen.buyers.activity.R.id.recent_category_flow_layout));
        initViewData();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public SearchFragment build() {
            SearchFragment_ fragment_ = new SearchFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
