//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.micen.buyers.activity.rfq;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import com.micen.buyers.activity.R.id;
import com.micen.buyers.view.ScrollEditText;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class RFQPostBaseActivity_
    extends RFQPostBaseActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static RFQPostBaseActivity_.IntentBuilder_ intent(Context context) {
        return new RFQPostBaseActivity_.IntentBuilder_(context);
    }

    public static RFQPostBaseActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new RFQPostBaseActivity_.IntentBuilder_(fragment);
    }

    public static RFQPostBaseActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new RFQPostBaseActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        titleRightButton1 = ((ImageView) hasViews.findViewById(id.common_title_right_button1));
        titleRightButton2 = ((ImageView) hasViews.findViewById(id.common_title_right_button2));
        titleText = ((TextView) hasViews.findViewById(id.common_title_name));
        titleLeftButton = ((ImageView) hasViews.findViewById(id.common_title_back_button));
        titleRightButton3 = ((ImageView) hasViews.findViewById(id.common_title_right_button3));
        captureLayout = ((LinearLayout) hasViews.findViewById(id.mic_rfq_capture_layout));
        categoryText = ((TextView) hasViews.findViewById(id.mic_rfq_category));
        shipmentTermsLayout = ((LinearLayout) hasViews.findViewById(id.mic_rfq_termsDetailed_layout));
        piecesEdit = ((EditText) hasViews.findViewById(id.mic_rfq_pieces));
        descriptionEdit = ((ScrollEditText) hasViews.findViewById(id.mic_rfq_edit_description));
        shipmentTermsText = ((TextView) hasViews.findViewById(id.mic_rfq_shipmentTerms));
        optionalLayout = ((LinearLayout) hasViews.findViewById(id.mic_rfq_optional_layout));
        supplierLayout = ((LinearLayout) hasViews.findViewById(id.mic_rfq_supplier_layout));
        productNameEdit = ((EditText) hasViews.findViewById(id.mic_rfq_edit_productName));
        tradingLayout = ((LinearLayout) hasViews.findViewById(id.mic_rfq_trading_layout));
        moreMsgLayout = ((LinearLayout) hasViews.findViewById(id.mic_rfq_more_layout));
        requirementsToSupplierLayout = ((LinearLayout) hasViews.findViewById(id.mic_rfq_requirementsToSupplier_layout));
        fobText = ((TextView) hasViews.findViewById(id.mic_rfq_fob));
        baseLayout = ((RelativeLayout) hasViews.findViewById(id.mic_rfq_layout));
        requirementsForTradingLayout = ((LinearLayout) hasViews.findViewById(id.mic_rfq_requirementsForTrading_layout));
        targetPriceEdit = ((EditText) hasViews.findViewById(id.mic_rfq_edit_targetPrice));
        expiredDateText = ((TextView) hasViews.findViewById(id.mic_rfq_expiredDate));
        purchaseQuantityEdit = ((EditText) hasViews.findViewById(id.mic_rfq_purchaseQuantity));
        destinationPortEdit = ((EditText) hasViews.findViewById(id.mic_rfq_edit_destinationPort));
        baseScrollView = ((ScrollView) hasViews.findViewById(id.mic_rfq_scrollView));
        usdEdit = ((EditText) hasViews.findViewById(id.mic_rfq_usd));
        paymentTermsEdit = ((EditText) hasViews.findViewById(id.mic_rfq_paymentTerms));
        initView();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, RFQPostBaseActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, RFQPostBaseActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, RFQPostBaseActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public RFQPostBaseActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
