//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.micen.buyers.activity.message;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import com.micen.buyers.activity.R.id;
import com.micen.buyers.view.SearchListProgressBar;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MailDetailActivity_
    extends MailDetailActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MailDetailActivity_.IntentBuilder_ intent(Context context) {
        return new MailDetailActivity_.IntentBuilder_(context);
    }

    public static MailDetailActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new MailDetailActivity_.IntentBuilder_(fragment);
    }

    public static MailDetailActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new MailDetailActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        titleRightButton2 = ((ImageView) hasViews.findViewById(id.common_title_right_button2));
        titleLeftButton = ((ImageView) hasViews.findViewById(id.common_title_back_button));
        titleText = ((TextView) hasViews.findViewById(id.common_title_name));
        titleRightButton3 = ((ImageView) hasViews.findViewById(id.common_title_right_button3));
        titleRightButton1 = ((ImageView) hasViews.findViewById(id.common_title_right_button1));
        mailFrom = ((TextView) hasViews.findViewById(id.tv_mail_from_value));
        mailTo = ((TextView) hasViews.findViewById(id.tv_mail_to_value));
        iv_next = ((ImageView) hasViews.findViewById(id.ic_bottom_bar4));
        mailDetailScroll = ((ScrollView) hasViews.findViewById(id.mail_detail_scroll));
        iv_repaly = ((ImageView) hasViews.findViewById(id.ic_bottom_bar1));
        mailContent = ((TextView) hasViews.findViewById(id.tv_mail_content));
        mailData = ((TextView) hasViews.findViewById(id.tv_mail_data));
        iv_pre = ((ImageView) hasViews.findViewById(id.ic_bottom_bar3));
        bottomBarLayout = ((LinearLayout) hasViews.findViewById(id.mail_detail_bottom_layout));
        mailTitle = ((TextView) hasViews.findViewById(id.tv_mail_title));
        progressBar = ((SearchListProgressBar) hasViews.findViewById(id.progressbar_layout));
        iv_delete = ((ImageView) hasViews.findViewById(id.ic_bottom_bar2));
        initView();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MailDetailActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, MailDetailActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, MailDetailActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MailDetailActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
