//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.micen.buyers.activity.message;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import com.micen.buyers.activity.R.id;
import com.micen.buyers.view.SearchListProgressBar;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MailPersonalActivity_
    extends MailPersonalActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MailPersonalActivity_.IntentBuilder_ intent(Context context) {
        return new MailPersonalActivity_.IntentBuilder_(context);
    }

    public static MailPersonalActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new MailPersonalActivity_.IntentBuilder_(fragment);
    }

    public static MailPersonalActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new MailPersonalActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        titleRightButton1 = ((ImageView) hasViews.findViewById(id.common_title_right_button1));
        titleRightButton2 = ((ImageView) hasViews.findViewById(id.common_title_right_button2));
        titleText = ((TextView) hasViews.findViewById(id.common_title_name));
        titleRightButton3 = ((ImageView) hasViews.findViewById(id.common_title_right_button3));
        titleLeftButton = ((ImageView) hasViews.findViewById(id.common_title_back_button));
        personalWebsiteLayout = ((RelativeLayout) hasViews.findViewById(id.rl_personal_website));
        icPersonalEmail = ((ImageView) hasViews.findViewById(id.iv_personal_email));
        personalCompany = ((TextView) hasViews.findViewById(id.tv_personal_company));
        personalEmailLayout = ((RelativeLayout) hasViews.findViewById(id.rl_personal_email));
        tvPersonalCountry = ((TextView) hasViews.findViewById(id.tv_personal_country_value));
        personalTelLayout = ((RelativeLayout) hasViews.findViewById(id.rl_personal_tel));
        personalType = ((ImageView) hasViews.findViewById(id.iv_personal_type));
        personalScroll = ((ScrollView) hasViews.findViewById(id.mail_personal_scroll));
        tvPersonalFax = ((TextView) hasViews.findViewById(id.tv_personal_fax_value));
        personalFaxLayout = ((RelativeLayout) hasViews.findViewById(id.rl_personal_fax));
        tvPersonalWebsite = ((TextView) hasViews.findViewById(id.tv_personal_website_value));
        personalName = ((TextView) hasViews.findViewById(id.tv_personal_name));
        personalCountryLayout = ((RelativeLayout) hasViews.findViewById(id.rl_personal_country));
        tvPersonalTel = ((TextView) hasViews.findViewById(id.tv_personal_tel_value));
        personalTitle = ((RelativeLayout) hasViews.findViewById(id.rl_personal_title));
        icPersonalTel = ((ImageView) hasViews.findViewById(id.iv_personal_tel));
        progressBar = ((SearchListProgressBar) hasViews.findViewById(id.progressbar_layout));
        icPersonalWebsite = ((ImageView) hasViews.findViewById(id.iv_personal_website));
        tvPersonalEmail = ((TextView) hasViews.findViewById(id.tv_personal_email_value));
        initView();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MailPersonalActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, MailPersonalActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, MailPersonalActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MailPersonalActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
