//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.micen.buyers.activity.searchresult;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.micen.buyers.activity.R.id;
import com.micen.buyers.activity.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class CompanySearchListActivity_
    extends CompanySearchListActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String KEYWORD_EXTRA = "keyword";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_search_list);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static CompanySearchListActivity_.IntentBuilder_ intent(Context context) {
        return new CompanySearchListActivity_.IntentBuilder_(context);
    }

    public static CompanySearchListActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new CompanySearchListActivity_.IntentBuilder_(fragment);
    }

    public static CompanySearchListActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new CompanySearchListActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        modeImageView = ((ImageView) hasViews.findViewById(id.iv_search_list_mode));
        iv_search = ((ImageView) hasViews.findViewById(id.iv_search));
        suggestLayout = ((LinearLayout) hasViews.findViewById(id.search_suggest_layout));
        backTopImageView = ((ImageView) hasViews.findViewById(id.iv_scroll_top));
        titleLeftButton = ((ImageView) hasViews.findViewById(id.common_title_back_button));
        searchListLayout = ((RelativeLayout) hasViews.findViewById(id.search_list_layout));
        titleText = ((TextView) hasViews.findViewById(id.common_title_name));
        titleRightButton1 = ((ImageView) hasViews.findViewById(id.common_title_right_button1));
        progressLayout = ((RelativeLayout) hasViews.findViewById(id.progressbar_layout));
        tvNoMatch = ((TextView) hasViews.findViewById(id.tv_search_noMatch));
        titleRightButton3 = ((ImageView) hasViews.findViewById(id.common_title_right_button3));
        titleRightButton2 = ((ImageView) hasViews.findViewById(id.common_title_right_button2));
        seachTextView = ((TextView) hasViews.findViewById(id.search_name_text_view));
        tvSuggest = ((TextView) hasViews.findViewById(id.tv_search_suggest));
        loadingLayout = ((RelativeLayout) hasViews.findViewById(id.loading_bar));
        searchLayout = ((LinearLayout) hasViews.findViewById(id.search_again_layout));
        initViewData();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(KEYWORD_EXTRA)) {
                keyword = extras_.getString(KEYWORD_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, CompanySearchListActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, CompanySearchListActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, CompanySearchListActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public CompanySearchListActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public CompanySearchListActivity_.IntentBuilder_ keyword(String keyword) {
            intent_.putExtra(KEYWORD_EXTRA, keyword);
            return this;
        }

    }

}
