//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.micen.buyers.activity.searchresult;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.micen.buyers.activity.R.id;
import com.micen.buyers.activity.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ProductSearchListActivity_
    extends ProductSearchListActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String KEYWORD_EXTRA = "keyword";
    public final static String CATEGORY_EXTRA = "category";
    public final static String IS_CATEGORY_EXTRA = "isCategory";
    public final static String SEARCH_TYPE_STRING_EXTRA = "searchType";
    public final static String SOURCE_SUBJECT_EXTRA = "sourceSubject";
    public final static String COMPANY_ID_EXTRA = "companyId";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_search_list);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ProductSearchListActivity_.IntentBuilder_ intent(Context context) {
        return new ProductSearchListActivity_.IntentBuilder_(context);
    }

    public static ProductSearchListActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new ProductSearchListActivity_.IntentBuilder_(fragment);
    }

    public static ProductSearchListActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new ProductSearchListActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        titleRightButton3 = ((ImageView) hasViews.findViewById(id.common_title_right_button3));
        titleRightButton1 = ((ImageView) hasViews.findViewById(id.common_title_right_button1));
        backTopImageView = ((ImageView) hasViews.findViewById(id.iv_scroll_top));
        modeImageView = ((ImageView) hasViews.findViewById(id.iv_search_list_mode));
        titleLeftButton = ((ImageView) hasViews.findViewById(id.common_title_back_button));
        searchLayout = ((LinearLayout) hasViews.findViewById(id.search_again_layout));
        tvSuggest = ((TextView) hasViews.findViewById(id.tv_search_suggest));
        seachTextView = ((TextView) hasViews.findViewById(id.search_name_text_view));
        progressLayout = ((RelativeLayout) hasViews.findViewById(id.progressbar_layout));
        searchListLayout = ((RelativeLayout) hasViews.findViewById(id.search_list_layout));
        titleRightButton2 = ((ImageView) hasViews.findViewById(id.common_title_right_button2));
        loadingLayout = ((RelativeLayout) hasViews.findViewById(id.loading_bar));
        iv_search = ((ImageView) hasViews.findViewById(id.iv_search));
        suggestLayout = ((LinearLayout) hasViews.findViewById(id.search_suggest_layout));
        tvNoMatch = ((TextView) hasViews.findViewById(id.tv_search_noMatch));
        titleText = ((TextView) hasViews.findViewById(id.common_title_name));
        initData();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(KEYWORD_EXTRA)) {
                keyword = extras_.getString(KEYWORD_EXTRA);
            }
            if (extras_.containsKey(CATEGORY_EXTRA)) {
                category = extras_.getString(CATEGORY_EXTRA);
            }
            if (extras_.containsKey(IS_CATEGORY_EXTRA)) {
                isCategory = extras_.getBoolean(IS_CATEGORY_EXTRA);
            }
            if (extras_.containsKey(SEARCH_TYPE_STRING_EXTRA)) {
                searchTypeString = extras_.getString(SEARCH_TYPE_STRING_EXTRA);
            }
            if (extras_.containsKey(SOURCE_SUBJECT_EXTRA)) {
                sourceSubject = extras_.getString(SOURCE_SUBJECT_EXTRA);
            }
            if (extras_.containsKey(COMPANY_ID_EXTRA)) {
                companyId = extras_.getString(COMPANY_ID_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ProductSearchListActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ProductSearchListActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ProductSearchListActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ProductSearchListActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public ProductSearchListActivity_.IntentBuilder_ keyword(String keyword) {
            intent_.putExtra(KEYWORD_EXTRA, keyword);
            return this;
        }

        public ProductSearchListActivity_.IntentBuilder_ category(String category) {
            intent_.putExtra(CATEGORY_EXTRA, category);
            return this;
        }

        public ProductSearchListActivity_.IntentBuilder_ isCategory(boolean isCategory) {
            intent_.putExtra(IS_CATEGORY_EXTRA, isCategory);
            return this;
        }

        public ProductSearchListActivity_.IntentBuilder_ searchTypeString(String searchTypeString) {
            intent_.putExtra(SEARCH_TYPE_STRING_EXTRA, searchTypeString);
            return this;
        }

        public ProductSearchListActivity_.IntentBuilder_ sourceSubject(String sourceSubject) {
            intent_.putExtra(SOURCE_SUBJECT_EXTRA, sourceSubject);
            return this;
        }

        public ProductSearchListActivity_.IntentBuilder_ companyId(String companyId) {
            intent_.putExtra(COMPANY_ID_EXTRA, companyId);
            return this;
        }

    }

}
