//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.micen.buyers.activity.showroom;

import java.io.Serializable;
import java.util.ArrayList;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ExpandableListView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.micen.buyers.activity.R.id;
import com.micen.buyers.activity.R.layout;
import com.micen.buyers.module.showroom.ProductGroup;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ProductRefineActivity_
    extends ProductRefineActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String COMPANY_ID_EXTRA = "companyId";
    public final static String MEMBER_TYPE_EXTRA = "memberType";
    public final static String PRODUCT_GROUP_EXTRA = "productGroup";
    public final static String SELECTED_GROUP_EXTRA = "selectedGroup";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_product_refine);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ProductRefineActivity_.IntentBuilder_ intent(Context context) {
        return new ProductRefineActivity_.IntentBuilder_(context);
    }

    public static ProductRefineActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new ProductRefineActivity_.IntentBuilder_(fragment);
    }

    public static ProductRefineActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new ProductRefineActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        titleRightButton3 = ((ImageView) hasViews.findViewById(id.common_title_right_button3));
        titleLeftButton = ((ImageView) hasViews.findViewById(id.common_title_back_button));
        titleText = ((TextView) hasViews.findViewById(id.common_title_name));
        titleRightButton2 = ((ImageView) hasViews.findViewById(id.common_title_right_button2));
        titleRightButton1 = ((ImageView) hasViews.findViewById(id.common_title_right_button1));
        header = ((LinearLayout) hasViews.findViewById(id.header));
        listView = ((ExpandableListView) hasViews.findViewById(id.product_group_list));
        emptyView = ((ImageView) hasViews.findViewById(id.empty_view));
        init();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(COMPANY_ID_EXTRA)) {
                companyId = extras_.getString(COMPANY_ID_EXTRA);
            }
            if (extras_.containsKey(MEMBER_TYPE_EXTRA)) {
                memberType = extras_.getString(MEMBER_TYPE_EXTRA);
            }
            if (extras_.containsKey(PRODUCT_GROUP_EXTRA)) {
                productGroup = extras_.getParcelableArrayList(PRODUCT_GROUP_EXTRA);
            }
            if (extras_.containsKey(SELECTED_GROUP_EXTRA)) {
                selectedGroup = extras_.getParcelable(SELECTED_GROUP_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ProductRefineActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ProductRefineActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ProductRefineActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ProductRefineActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public ProductRefineActivity_.IntentBuilder_ companyId(String companyId) {
            intent_.putExtra(COMPANY_ID_EXTRA, companyId);
            return this;
        }

        public ProductRefineActivity_.IntentBuilder_ memberType(String memberType) {
            intent_.putExtra(MEMBER_TYPE_EXTRA, memberType);
            return this;
        }

        public ProductRefineActivity_.IntentBuilder_ productGroup(ArrayList<ProductGroup> productGroup) {
            intent_.putExtra(PRODUCT_GROUP_EXTRA, ((Serializable) productGroup));
            return this;
        }

        public ProductRefineActivity_.IntentBuilder_ selectedGroup(ProductGroup selectedGroup) {
            intent_.putExtra(SELECTED_GROUP_EXTRA, selectedGroup);
            return this;
        }

    }

}
