//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.micen.buyers.activity.showroom;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.micen.buyers.activity.R.id;
import com.micen.buyers.activity.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ProductSearchActivity_
    extends ProductSearchActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String COMPANY_ID_EXTRA = "companyId";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_product_search);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ProductSearchActivity_.IntentBuilder_ intent(Context context) {
        return new ProductSearchActivity_.IntentBuilder_(context);
    }

    public static ProductSearchActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new ProductSearchActivity_.IntentBuilder_(fragment);
    }

    public static ProductSearchActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new ProductSearchActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        keywordEdit = ((EditText) hasViews.findViewById(id.keyword_edit));
        progressLayout = ((RelativeLayout) hasViews.findViewById(id.progressbar_layout));
        modeImageView = ((ImageView) hasViews.findViewById(id.iv_search_list_mode));
        suggestLayout = ((LinearLayout) hasViews.findViewById(id.search_suggest_layout));
        titleLeftButton = ((ImageView) hasViews.findViewById(id.title_back_button));
        loadingLayout = ((RelativeLayout) hasViews.findViewById(id.loading_bar));
        clearTag = ((ImageView) hasViews.findViewById(id.clear_keyword));
        searchListLayout = ((RelativeLayout) hasViews.findViewById(id.search_list_layout));
        scrollTopImageView = ((ImageView) hasViews.findViewById(id.iv_scroll_top));
        tvNoMatch = ((TextView) hasViews.findViewById(id.tv_search_noMatch));
        initData();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(COMPANY_ID_EXTRA)) {
                companyId = extras_.getString(COMPANY_ID_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ProductSearchActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ProductSearchActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ProductSearchActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ProductSearchActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public ProductSearchActivity_.IntentBuilder_ companyId(String companyId) {
            intent_.putExtra(COMPANY_ID_EXTRA, companyId);
            return this;
        }

    }

}
