//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.micen.buyers.activity.category;

import java.io.Serializable;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.micen.buyers.activity.R.id;
import com.micen.buyers.activity.R.layout;
import com.micen.buyers.module.category.Category;
import com.micen.buyers.view.SearchListProgressBar;
import com.micen.buyers.widget.pinnerexpandview.PinnedHeaderExpandableListView;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class CategorySecondActivity_
    extends CategorySecondActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String FATHER_CATEGORY_EXTRA = "Category";
    public final static String IS_SEARCH_CATEGORY_EXTRA = "isSearchCategory";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_category_second);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static CategorySecondActivity_.IntentBuilder_ intent(Context context) {
        return new CategorySecondActivity_.IntentBuilder_(context);
    }

    public static CategorySecondActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new CategorySecondActivity_.IntentBuilder_(fragment);
    }

    public static CategorySecondActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new CategorySecondActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        titleLeftButton = ((ImageView) hasViews.findViewById(id.common_title_back_button));
        titleRightButton1 = ((ImageView) hasViews.findViewById(id.common_title_right_button1));
        titleRightButton3 = ((ImageView) hasViews.findViewById(id.common_title_right_button3));
        titleText = ((TextView) hasViews.findViewById(id.common_title_name));
        titleRightButton2 = ((ImageView) hasViews.findViewById(id.common_title_right_button2));
        secondCategoryListView = ((PinnedHeaderExpandableListView) hasViews.findViewById(id.second_expandablelist));
        progressLayout = ((SearchListProgressBar) hasViews.findViewById(id.progressbar_layout));
        stickyLayout = ((LinearLayout) hasViews.findViewById(id.sticky_content));
        searchLayout = ((RelativeLayout) hasViews.findViewById(id.search_title_layout));
        initViewData();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(FATHER_CATEGORY_EXTRA)) {
                fatherCategory = ((Category) extras_.getSerializable(FATHER_CATEGORY_EXTRA));
            }
            if (extras_.containsKey(IS_SEARCH_CATEGORY_EXTRA)) {
                isSearchCategory = extras_.getBoolean(IS_SEARCH_CATEGORY_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, CategorySecondActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, CategorySecondActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, CategorySecondActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public CategorySecondActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

        public CategorySecondActivity_.IntentBuilder_ fatherCategory(Category fatherCategory) {
            intent_.putExtra(FATHER_CATEGORY_EXTRA, ((Serializable) fatherCategory));
            return this;
        }

        public CategorySecondActivity_.IntentBuilder_ isSearchCategory(boolean isSearchCategory) {
            intent_.putExtra(IS_SEARCH_CATEGORY_EXTRA, isSearchCategory);
            return this;
        }

    }

}
