//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.micen.buyers.view.mail;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MailSendBaseFragment_
    extends MailSendBaseFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MailSendBaseFragment_.FragmentBuilder_ builder() {
        return new MailSendBaseFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        subjectInput = ((EditText) hasViews.findViewById(com.micen.buyers.activity.R.id.mail_send_subject_input));
        mailTo = ((TextView) hasViews.findViewById(com.micen.buyers.activity.R.id.tv_mail_to_value));
        btnShortcut = ((TextView) hasViews.findViewById(com.micen.buyers.activity.R.id.tv_mail_send_shortcut));
        mailFrom = ((TextView) hasViews.findViewById(com.micen.buyers.activity.R.id.tv_mail_from_value));
        clearImage = ((ImageView) hasViews.findViewById(com.micen.buyers.activity.R.id.mail_send_subject_clear));
        contentInput = ((EditText) hasViews.findViewById(com.micen.buyers.activity.R.id.tv_mail_send_content));
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public MailSendBaseFragment build() {
            MailSendBaseFragment_ fragment_ = new MailSendBaseFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
